version: '3.8'

services:
  backend:
    image: farisgebril/todo-app-backend:latest
    container_name: todo-backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - PORT=8081
